local addonName, addonTable = ...; -- Pulls back the Addon-Local Variables and store them locally.
local FORCE_DEBUG = false;

if LunaEclipse_Scripts:isCompatableWOWVersion() and LunaEclipse_Scripts:isRequiredOvaleVersion(addonTable.REQUIRED_OVALE_VERSION) then
	local OvaleScripts = addonTable.Ovale.OvaleScripts;

	do
		local name = "lunaeclipse_mage_spells";
		local desc = "LunaEclipse: Mage spells";
		local code = [[
			# Mage spells and functions.

			Define(arcane_affinity 166871)
				SpellInfo(arcane_affinity duration=15)
			Define(arcane_barrage 44425)
				SpellInfo(arcane_barrage cd=4.5 haste=spell travel_time=1 arcanecharges=0)
			Define(arcane_blast 30451)
				SpellInfo(arcane_blast arcanecharges=-1)
				SpellAddBuff(arcane_blast presence_of_mind_buff=-1)
				SpellAddBuff(arcane_blast profound_magic_buff=0 itemset=T16_caster itemcount=2 specialization=arcane)
			Define(arcane_brilliance 1459)
				SpellAddBuff(arcane_brilliance arcane_brilliance_buff=1)
			Define(arcane_brilliance_buff 1459)
				SpellInfo(arcane_brilliance_buff duration=3600)
			Define(arcane_charge 114664)
			Define(arcane_charge_debuff 36032)
				SpellInfo(arcane_charge_debuff duration=15 max_stacks=4)
			Define(arcane_explosion 1449)
				SpellInfo(arcane_explosion arcanecharges=-1)
			Define(arcane_familiar 205022)
				SpellInfo(arcane_familiar cd=10 gcd=1.5)
				SpellAddBuff(arcane_familiar arcane_familiar_buff=1)
			Define(arcane_familiar_buff 210126)
				SpellInfo(arcane_familiar_buff duration=3600)
			Define(arcane_instability_buff 166872)
				SpellInfo(arcane_instability_buff duration=15)
			Define(arcane_missiles 5143)
				SpellInfo(arcane_missiles duration=2 travel_time=1 arcanecharges=-1)
				SpellRequire(arcane_missiles unusable 1=buff,!arcane_missiles_buff)
				SpellAddBuff(arcane_missiles arcane_instability_buff=0 itemset=T17 itemcount=4 specialization=arcane)
				SpellAddBuff(arcane_missiles arcane_missiles_buff=-1)
			Define(arcane_missiles_buff 79683)
				SpellInfo(arcane_missiles_buff duration=20 max_stacks=3)
			Define(arcane_orb 153626)
				SpellInfo(arcane_orb cd=20)
			Define(arcane_power 12042)
				SpellInfo(arcane_power cd=90 gcd=0)
				SpellAddBuff(arcane_power arcane_power_buff=1)
			Define(arcane_power_buff 12042)
				SpellInfo(arcane_power_buff duration=10)
			Define(blast_wave 157981)
			Define(blazing_barrier 235313)
				SpellInfo(blazing_barrier cd=25)
			Define(blazing_barrier_buff 235313)
				SpellInfo(blazing_barrier_buff duration=60)
			Define(blazing_speed 108843)
				SpellInfo(blazing_speed cd=25 gcd=0 offgcd=1)
			Define(blink 1953)
				SpellInfo(blink cd=15)
			Define(blizzard 190356)
				SpellInfo(blizzard channel=8 cd=8 haste=spell)
				SpellAddBuff(blizzard ice_floes_buff=0 if_spell=ice_floes)
			Define(brain_freeze_buff 190446)
				SpellInfo(brain_freeze_buff duration=15)
			Define(charged_up 205032)
				SpellInfo(charged_up arcanecharges=-4)
			Define(chilled_to_the_core 195448)
			Define(cinderstorm 198929)
				SpellInfo(cinderstorm cd=9)
			Define(cold_snap 11958)
				SpellInfo(cold_snap cd=180 gcd=0 offgcd=1)
			Define(combustion 190319)
				SpellInfo(combustion cd=120 gcd=0)
				SpellAddBuff(combustion combustion_buff=1)
			Define(combustion_buff 190319)
				SpellInfo(combustion_buff duration=10)
			Define(comet_storm 153595)
				SpellInfo(comet_storm cd=30 travel_time=1)
			Define(cone_of_cold 120)
				SpellInfo(cone_of_cold cd=12)
			Define(counterspell 2139)
				SpellInfo(counterspell cd=24 gcd=0 interrupt=1)
			Define(deep_freeze 44572)
				SpellInfo(deep_freeze cd=30 interrupt=1)
				SpellAddBuff(deep_freeze fingers_of_frost_buff=-1 if_spell=fingers_of_frost)
			Define(dragons_breath 31661)
				SpellInfo(dragons_breath cd=20)
			Define(evocation 12051)
				SpellInfo(evocation cd=120 channel=3 haste=spell)
				SpellInfo(evocation addcd=-30 if_spell=improved_evocation)
				SpellAddBuff(evocation ice_floes_buff=0 if_spell=ice_floes)
			Define(fingers_of_frost_buff 44544)
				SpellInfo(fingers_of_frost_buff duration=15 max_stacks=2)
				SpellInfo(fingers_of_frost_buff max_stacks=4 itemset=T18 itemcount=4)
			Define(fire_blast 108853)
				SpellInfo(fire_blast cd=12 gcd=0 offgcd=1)
			Define(fireball 133)
			Define(flamestrike 2120)
				SpellInfo(flamestrike cd=12)
				SpellInfo(flamestrike cd=0 if_spell=improved_flamestrike)
				SpellAddBuff(flamestrike ice_floes_buff=0 if_spell=ice_floes)
				SpellAddTargetDebuff(flamestrike flamestrike_debuff=1)
				SpellAddBuff(flamestrike hot_streak_buff=0)
			Define(flamestrike_debuff 2120)
				SpellInfo(flamestrike_debuff duration=8 haste=spell tick=2)
			Define(flurry 44614)
				SpellAddBuff(flurry brain_freeze_buff=-1)
				SpellAddTargetDebuff(flurry winters_chill_debuff=1)
			Define(frost_bomb 112948)
				SpellAddTargetDebuff(frost_bomb frost_bomb_debuff=1)
			Define(freezing_rain_buff 240555)
				SpellInfo(freezing_rain_buff duration=15)
			Define(frost_bomb_debuff 112948)
				SpellInfo(frost_bomb_debuff duration=12)
			Define(frost_nova 122)
			Define(frostbolt 116)
				SpellInfo(frostbolt travel_time=1)
				SpellAddBuff(frostbolt ice_floes_buff=0 if_spell=ice_floes)
				SpellAddBuff(frostbolt icicles_buff=1)
			Define(frostfire_bolt 44614)
				SpellInfo(frostfire_bolt travel_time=1)
				SpellAddBuff(frostfire_bolt brain_freeze_buff=0 if_spell=brain_freeze_buff)
				SpellAddBuff(frostfire_bolt ice_floes_buff=0 if_spell=ice_floes)
			Define(frozen_orb 84714)
				SpellInfo(frozen_orb cd=60 travel_time=10)
			Define(frozen_orb_debuff 84721)
				SpellInfo(frozen_orb_debuff duration=2)
			Define(frozen_touch 205030)
				SpellInfo(frozen_touch cd=30)
				SpellAddBuff(frozen_touch fingers_of_frost_buff=2)
			Define(glacial_spike 199786)
				SpellInfo(glacial_spike mana=1 unusable=1)
				SpellRequire(glacial_spike unusable 0=buff,icicles_buff,5)
				SpellAddBuff(glacial_spike icicles_buff=0)
			Define(heating_up_buff 48107)
				SpellInfo(heating_up_buff duration=10)
			Define(hot_streak_buff 48108)
			Define(hypothermia_debuff 41425)
				SpellInfo(hypothermia_debuff duration=30)
			Define(ice_barrier 11426)
				SpellInfo(ice_barrier cd=25)
			Define(ice_barrier_buff 11426)
				SpellInfo(ice_barrier_buff duration=60)
			Define(ice_block 45438)
				SpellInfo(ice_block cd=300 gcd=1.5)
				SpellAddBuff(ice_block ice_block_buff=1)
			Define(ice_block_buff 45438)
				SpellInfo(ice_block_buff duration=10)
			Define(ice_floes 108839)
				SpellAddBuff(ice_floes ice_floes_buff=1)
			Define(ice_floes_buff 108839)
				SpellInfo(ice_floes_buff duration=15)
			Define(ice_lance 30455)
				SpellAddBuff(ice_lance fingers_of_frost_buff=-1 if_spell=fingers_of_frost)
				#SpellAddBuff(ice_lance icy_veins_buff=extend,1 talent=thermal_void_talent)
				SpellAddBuff(ice_lance magtheridons_might_buff=1)
			Define(ice_nova 157997)
			Define(ice_shard_buff 166869)
				SpellInfo(ice_shard_buff duration=10 max_stacks=10)
			Define(icicles_buff 205473)
				SpellInfo(icicles_buff duration=60)
			Define(icy_hand 220817)
			Define(icy_veins 12472)
				SpellInfo(icy_veins cd=180)
				SpellInfo(icy_veins addcd=-90 itemset=T14 itemcount=4)
				SpellAddBuff(icy_veins icy_veins_buff=1)
			Define(icy_veins_buff 12472)
				SpellInfo(icy_veins_buff duration=20)
				SpellInfo(icy_veins_buff duration=30 talent=thermal_void_talent)
			Define(ignite_debuff 12654)
				SpellInfo(ignite_debuff duration=5 tick=1)
			Define(improved_evocation 157614)
			Define(improved_flamestrike 157621)
			Define(incanters_flow 1463)
			Define(incanters_flow_buff 116267)
				SpellInfo(incanters_flow_buff duration=25 max_stacks=5)
			Define(inferno_blast 108853)
				SpellInfo(inferno_blast cd=8)
				SpellInfo(inferno_blast addcd=-2 itemset=T17 itemcount=2)
			Define(kaelthas_ultimate_ability_buff 209455)
			Define(living_bomb 44457)
				SpellInfo(living_bomb gcd=1)
				SpellAddTargetDebuff(living_bomb living_bomb_debuff=1)
			Define(living_bomb_debuff 44457)
				SpellInfo(living_bomb duration=12 haste=spell tick=3)
			Define(mark_of_doom_debuff 184073)
				SpellInfo(mark_of_doom_debuff duration=10)
			Define(meteor 153561)
				SpellInfo(meteor cd=45 travel_time=1)
			Define(mirror_image 55342)
				SpellInfo(mirror_image cd=120)
			Define(nether_tempest 114923)
				SpellAddTargetDebuff(nether_tempest nether_tempest_debuff=1)
			Define(nether_tempest_debuff 114923)
				SpellInfo(nether_tempest_debuff duration=12 haste=spell tick=1)
			Define(overpowered 155147)
			Define(polymorph 118)
				SpellAddTargetDebuff(polymorph polymorph_debuff=1)
			Define(polymorph_debuff 118)
				SpellInfo(polymorph_debuff duration=50)
			Define(potent_flames_buff 145254)
				SpellInfo(potent_flames_buff duration=5 max_stacks=5)
			Define(presence_of_mind 205025)
				SpellInfo(presence_of_mind cd=90 gcd=0)
				SpellInfo(presence_of_mind arcanecharges=-4 itemset=T20 itemcount=2)
				SpellAddBuff(presence_of_mind presence_of_mind_buff=2)
			Define(presence_of_mind_buff 205025)
			Define(prismatic_barrier 235450)
				SpellInfo(prismatic_barrier cd=25)
				SpellAddBuff(prismatic_barrier prismatic_barrier_buff=1)
			Define(prismatic_barrier_buff 235450)
				SpellInfo(prismatic_barrier_buff duration=60)
			Define(profound_magic_buff 145252)
				SpellInfo(profound_magic_buff duration=10 max_stacks=4)
			Define(prismatic_crystal 152087)
				SpellInfo(prismatic_crystal cd=90 duration=12 totem=1)
			Define(pyroblast 11366)
				SpellInfo(pyroblast travel_time=1)
				SpellInfo(pyroblast damage=FirePyroblastHitDamage specialization=fire)
				SpellAddBuff(pyroblast ice_floes_buff=0 if_spell=ice_floes)
				SpellAddBuff(pyroblast pyroblast_buff=0)
				SpellAddTargetDebuff(pyroblast pyroblast_debuff=1)
				SpellAddBuff(pyroblast hot_streak_buff=0)
			Define(pyroblast_buff 48108)
				SpellInfo(pyroblast_buff duration=15)
			Define(pyroblast_debuff 11366)
				SpellInfo(pyroblast_debuff duration=18 haste=spell tick=3)
			Define(pyromaniac_buff 166868)
				SpellInfo(pyromaniac_buff duration=4)
			Define(quickening_buff 198924)
				SpellAddBuff(arcane_barrage quickening_buff=0)
			Define(ray_of_frost 205021)
				SpellInfo(ray_of_frost cd=60 channel=10)
			Define(rune_of_power 116011)
				SpellInfo(rune_of_power buff_totem=rune_of_power_buff max_charge=2 cd=40)
				SpellAddBuff(rune_of_power rune_of_power_buff=1)
			Define(rune_of_power_buff 116014)
				SpellInfo(rune_of_power_buff duration=10)
			Define(scorch 2948)
				SpellInfo(scorch travel_time=1)
			Define(shard_of_the_exodar_warp 207970)
			Define(spellsteal 30449)
			Define(supernova 157980)
				SpellInfo(supernova cd=25)
			Define(t18_class_trinket 124516)
			Define(temporal_displacement_debuff 80354)
				SpellInfo(temporal_displacement_debuff duration=600)
			Define(thermal_void 155149)
			Define(time_warp 80353)
				SpellInfo(time_warp cd=300 gcd=0)
				SpellAddBuff(time_warp time_warp_buff=1)
				SpellAddDebuff(time_warp temporal_displacement_debuff=1)
			Define(time_warp_buff 80353)
				SpellInfo(time_warp_buff duration=40)
			Define(water_elemental 31687)
				SpellInfo(water_elemental cd=60)
			Define(water_elemental_freeze 33395)
				SpellInfo(water_elemental_freeze cd=25 gcd=0 offgcd=1 sharedcd=water_elemental_water_jet)
				SpellAddBuff(water_elemental_freeze fingers_of_frost_buff=1 if_spell=fingers_of_frost)
			Define(water_elemental_water_jet 135029)
				SpellInfo(water_elemental_water_jet cd=25 gcd=0 offgcd=1)
				SpellAddBuff(water_elemental_water_jet brain_freeze_buff=1 itemset=T18 itemcount=2)
				SpellAddTargetDebuff(water_elemental_water_jet water_elemental_water_jet_debuff=1)
			Define(water_elemental_water_jet_debuff 135029)
				SpellInfo(water_elemental_water_jet_debuff duration=3.5)
				SpellInfo(water_elemental_water_jet_debuff addduration=10 itemset=T18 itemcount=4)
			Define(winters_chill_debuff 228358)
				SpellInfo(winters_chill_debuff duration=1)

			# Talents Common
			Define(mirror_image_talent 7)
			Define(rune_of_power_talent 8)
			Define(incanters_flow_talent 9)

			# Talents Arcane
			Define(arcane_familiar_talent 1)
			Define(presence_of_mind_talent 2)
			Define(slipstream_talent 5)
			Define(supernova_talent 10)
			Define(charged_up_talent 11)
			Define(resonance_talent 12)
			Define(nether_tempest_talent 16)
			Define(unstable_magic_talent 17)
			Define(overpowered_talent 19)
			Define(arcane_orb_talent 21)

			# Talents Fire
			Define(blast_wave_talent 5)
			Define(alexstraszas_fury_talent 10)
			Define(flame_on_talent 11)
			Define(living_bomb_talent 13)
			Define(flame_patch_talent 18)
			Define(kindling_talent 19)
			Define(cinderstorm_talent 20)
			Define(meteor_talent 21)

			# Talents Frost
			Define(ray_of_frost_talent 1)
			Define(lonely_winter_talent 2)
			Define(ice_flows_talent 5)
			Define(ice_nova_talent 10)
			Define(frozen_touch_talent 11)
			Define(splitting_ice_talent 12)
			Define(frost_bomb_talent 16)
			Define(unstable_magic_talent 17)
			Define(arctic_gale_talent 18)
			Define(thermal_void_talent 19)
			Define(glacial_spike_talent 20)	
			Define(comet_storm_talent 21)	

			# Artifacts
			Define(ebonbolt 214634)
				SpellInfo(ebonbolt cd=45)
				SpellAddBuff(ebonbolt brain_freeze_buff=1)
			Define(icy_hand 220817)
			Define(mark_of_aluneth 224968)
				SpellInfo(mark_of_aluneth cd=60)
				SpellAddTargetDebuff(mark_of_aluneth mark_of_aluneth_debuff=1)
			Define(mark_of_aluneth_debuff 224968)
				SpellInfo(mark_of_aluneth_debuff duration=6)
			Define(phoenix_reborn 215773)
			Define(phoenixs_flames 194466)
				SpellInfo(fire_blast gcd=1 cd=45)

			### Pyroblast
			AddFunction FirePyroblastHitDamage asValue=1 { 2.423 * Spellpower() * { BuffPresent(pyroblast_buff asValue=1) * 1.25 } }
		]];

		OvaleScripts:RegisterScript("MAGE", nil, name, desc, code, "include");
	end
end