local addonName, addonTable = ...; -- Pulls back the Addon-Local Variables and store them locally.
local FORCE_DEBUG = false;

if LunaEclipse_Scripts:isCompatableWOWVersion() and LunaEclipse_Scripts:isRequiredOvaleVersion(addonTable.REQUIRED_OVALE_VERSION) then
	local OvaleScripts = addonTable.Ovale.OvaleScripts;

	do
		local name = "lunaeclipse_warlock_spells";
		local desc = "LunaEclipse: Warlock spells";
		local code = [[
			# Warlock spells and functions.

			# Common Talents
			Define(empowered_life_tap_talent 6)
			Define(soul_harvest_talent 12)
			Define(dark_pact_talent 15)
			Define(grimoire_of_supremacy_talent 16)
			Define(grimoire_of_service_talent 17)
			Define(grimoire_of_sacrifice_talent 18)
			Define(soul_conduit_talent 21)

			# Affliction Talents
			Define(haunt_talent 1)
			Define(writhe_in_agony_talent 2)
			Define(malefic_grasp_talent 3)
			Define(contagion_talent 4)
			Define(absolute_corruption_talent 5)
			Define(siphon_life_talent 10)
			Define(sow_the_seeds_talent 11)
			Define(soul_effigy_talent 19)
			Define(phantom_singularity_talent 20)

			# Demonology Talents
			Define(shadowflame_talent 2)
			Define(impending_doom_talent 4)
			Define(implosion_talent 6)
			Define(hand_of_doom_talent 10)
			Define(power_trip_talent 11)
			Define(grimoire_of_synergy_talent 18)
			Define(summon_darkglare_talent 19)
			Define(demonbolt_talent 20)

			# Destruction Talents
			Define(roaring_blaze_talent 2)
			Define(shadowburn_talent 3)
			Define(cataclysm_talent 5)
			Define(eradication_talent 10)
			Define(dark_pact_talent 15)
			Define(wreak_havoc_talent 19)
			Define(channel_demonfire_talent 20)

			# Spells
			Define(agony 980)
				SpellInfo(agony gcd=1.5)
				SpellAddTargetDebuff(agony agony_debuff=1)
			Define(backdraft 117896)
			Define(call_dreadstalkers 104316)
				SpellInfo(call_dreadstalkers soulshards=2 cd=15)
			Define(cataclysm 152108)
				SpellInfo(cataclysm cd=60 gcd=0)
			Define(channel_demonfire 196447)
				SpellInfo(channel_demonfire cd=15 channel=3)
			Define(chaos_bolt 116858)
				SpellInfo(chaos_bolt gcd=1.5 soulshards=2 travel_time=1)
				SpellAddTargetDebuff(chaos_bolt eradication_debuff=1 talent=eradication_talent)
			Define(chaos_wave 124916)
				SpellInfo(chaos_wave demonicfury=80 travel_time=1)
				SpellAddBuff(chaos_wave fel_molten_core_aura=1 if_spell=the_codex_of_xerrath)
				SpellAddBuff(chaos_wave molten_core_aura=1 if_spell=!the_codex_of_xerrath)
			Define(charred_remains 157696)
			Define(conflagrate 17962)
				SpellInfo(conflagrate soulshards=-1 mana=600)
				SpellAddBuff(conflagrate havoc_buff=-1 if_spell=havoc)
			Define(corruption 172)
				SpellAddTargetDebuff(corruption corruption_debuff=1)
			Define(dark_intent 109773)
				SpellAddBuff(dark_intent dark_intent_buff=1)
			Define(dark_pact 108416)
				SpellInfo(dark_pact cd=60 gcd=0)
				SpellAddBuff(dark_pact dark_pact_buff=1)
			Define(dark_soul_instability 113858)
				SpellInfo(dark_soul_instability gcd=0)
				SpellAddBuff(dark_soul_instability dark_soul_instability_buff=1)
			Define(dark_soul_knowledge 113861)
				SpellInfo(dark_soul_knowledge gcd=0)
				SpellAddBuff(dark_soul_knowledge dark_soul_knowledge_buff=1)
			Define(dark_soul_misery 113860)
				SpellInfo(dark_soul_misery gcd=0)
				SpellAddBuff(dark_soul_misery dark_soul_misery_buff=1)
			Define(demonbolt 157695)
				SpellInfo(demonbolt soulshards=-1)
			Define(demonic_empowerment 193396)
				SpellRequire(demonic_empowerment unusable 1=pet_buff,demonic_empowerment)
				SpellAddPetBuff(demonic_empowerment demonic_empowerment=1)
			Define(demonwrath 193440)
			Define(doom 603)
				SpellInfo(doom gcd=1.5 soulshards=-1)
				SpellAddTargetDebuff(doom doom_debuff=1)
				SpellRequire(doom unusable 1=target_debuff,doom_debuff)
			Define(drain_life 689)
			Define(drain_soul 198590)
				SpellInfo(drain_soul channel=4 haste=spell)
			Define(enhanced_haunt 157072)
			Define(enhanced_havoc 157126)
			Define(fel_molten_core_aura 140074)
				SpellInfo(fel_molten_core_aura duration=30 max_stacks=10)
			Define(felguard_felstorm 89751)
				SpellInfo(felguard_felstorm cd=45 gcd=0)
			Define(fire_and_brimstone 108683)
				SpellInfo(fire_and_brimstone cd=1 gcd=0)
				SpellAddBuff(fire_and_brimstone fire_and_brimstone_buff=1)
			Define(grimoire_of_sacrifice 108503)
				SpellInfo(grimoire_of_sacrifice cd=30 gcd=0)
				SpellAddBuff(grimoire_of_sacrifice grimoire_of_sacrifice_buff=1)
			Define(hand_of_guldan 105174)
				SpellInfo(hand_of_guldan max_travel_time=1.5 shards=finisher) # maximum observed travel time with a bit of padding
				SpellAddTargetDebuff(hand_of_guldan shadowflame_debuff=1)
			Define(haunt 48181)
				SpellInfo(haunt soulshards=1)
				SpellInfo(haunt travel_time=2.3) # maximum observed travel time with a bit of padding
				SpellAddTargetDebuff(haunt haunt_debuff=1)
			Define(havoc 80240)
				SpellInfo(havoc cd=20 gcd=1.5)
				SpellInfo(havoc addcd=-20 talent=wreak_havoc_talent)
				SpellAddTargetDebuff(havoc havoc_debuff=1)			
			Define(hellfire 1949)
				SpellInfo(hellfire channel=14)
			Define(immolate 348)
				SpellAddBuff(immolate havoc_buff=-1 if_spell=havoc)
				SpellAddTargetDebuff(immolate immolate_debuff=1)
			Define(implosion 196277)
			Define(incinerate 29722)
				SpellInfo(incinerate travel_time=1)
				SpellAddBuff(incinerate backdraft_buff=-1 if_spell=backdraft)
				SpellAddBuff(incinerate havoc_buff=-1 if_spell=havoc)
				SpellAddTargetDebuff(incinerate flamelicked_debuff=1)
			Define(kiljaedens_cunning 137587)
				SpellInfo(kiljaedens_cunning cd=35 gcd=0)
				SpellAddBuff(kiljaedens_cunning kiljaedens_cunning_buff=1)
			Define(life_tap 1454)
				SpellAddBuff(life_tap empowered_life_tap_buff=1 talent=empowered_life_tap_talent)
			Define(lord_of_flames 224103)
			Define(mana_tap 196104)
				SpellAddBuff(mana_tap mana_tap_buff=1)
			Define(mannoroths_fury 108508)
				SpellInfo(mannoroths_fury cd=60 gcd=0)
				SpellAddBuff(mannoroths_fury mannoroths_fury_buff=1)
			Define(molten_core_aura 122355)
				SpellInfo(molten_core_aura duration=30 max_stacks=10)
			Define(phantom_singularity 205179)
				SpellInfo(phantom_singularity cd=60)
			Define(rain_of_fire 5740)
				SpellInfo(rain_of_fire channel=8 gcd=1.5 soulshards=3)
			Define(seed_of_corruption 27243)
				SpellRequire(seed_of_corruption replace seed_of_corruption_soulburn=buff,soulburn_buff if_spell=soulburn)
				SpellRequire(seed_of_corruption unusable 1=buff,soulburn_buff if_spell=soulburn)
				SpellAddTargetDebuff(seed_of_corruption seed_of_corruption_debuff=1)
			Define(seed_of_corruption_aura 27243)
				SpellInfo(seed_of_corruption_aura duration=18 tick=3)
			Define(seed_of_corruption_soulburn 114790)
				SpellRequire(seed_of_corruption_soulburn unusable 1=buff,!soulburn_buff)
				SpellAddTargetDebuff(seed_of_corruption_soulburn seed_of_corruption_soulburn_debuff=1)
			Define(service_doomguard 157900)
				SpellInfo(service_doomguard cd=120 sharedcd=service_pet soulshards=1)
			Define(service_felguard 111898)
				SpellInfo(service_felguard cd=120 sharedcd=service_pet soulshards=1)
			Define(service_felhunter 111897)
				SpellInfo(service_felhunter cd=120 sharedcd=service_pet soulshards=1)
			Define(service_imp 111859)
				SpellInfo(service_imp cd=120 sharedcd=service_pet soulshards=1)
			Define(service_infernal 157901)
				SpellInfo(service_infernal cd=120 sharedcd=service_pet soulshards=1)
			Define(service_succubus 111896)
				SpellInfo(service_succubus cd=120 sharedcd=service_pet soulshards=1)
			Define(service_pet 108501)
			Define(service_voidwalker 111895)
				SpellInfo(service_voidwalker cd=120 sharedcd=service_pet soulshards=1)
			Define(shadow_bolt 686)
				SpellInfo(shadow_bolt demonicfury=-25 specialization=demonology)
				SpellInfo(shadow_bolt travel_time=2.2) # maximum observed travel time with a bit of padding
				SpellAddBuff(shadow_bolt fel_molten_core_aura=1,target_health_pct,25 if_spell=the_codex_of_xerrath specialization=demonology)
				SpellAddBuff(shadow_bolt molten_core_aura=1,target_health_pct,25 if_spell=!the_codex_of_xerrath specialization=demonology)
			Define(shadowburn 17877)
				SpellInfo(shadowburn soulshards=1 target_health_pct=20)
				SpellAddBuff(shadowburn havoc_buff=-1 if_spell=havoc)
			Define(shadowflame 205181)
				SpellInfo(shadowflame cd=14 soulshards=-1)
			Define(siphon_life 63106)
				SpellAddTargetDebuff(siphon_life siphon_life_debuff=1)
			Define(soul_effigy 205178)
				SpellAddTargetDebuff(soul_effigy soul_effigy_debuff=1)
			Define(soul_fire 6353)
				SpellInfo(soul_fire demonicfury=-30 travel_time=1)
				SpellAddBuff(soul_fire fel_molten_core_aura=-1,target_health_pct,!25 if_spell=the_codex_of_xerrath)
				SpellAddBuff(soul_fire molten_core_aura=-1,target_health_pct,!25 if_spell=!the_codex_of_xerrath)
				SpellAddBuff(soul_fire demon_rush_buff=1 itemset=T18 itemcount=2 specialization=demonology)
			Define(soul_harvest 196098)
				SpellInfo(soul_harvest cd=120)
				SpellAddBuff(soul_harvest soul_harvest_buff=1)
			Define(soul_swap 86121)
				SpellInfo(soul_swap soulshards=1)
				SpellRequire(soul_swap replace soul_swap_soulburn=buff,soulburn_buff)
				SpellAddBuff(soul_swap soul_swap_buff=1)
			Define(soul_swap_exhale 86213)
				SpellAddBuff(soul_swap_exhale soul_swap_buff=0)
			Define(soul_swap_soulburn 119678)
				SpellInfo(soul_swap_soulburn soulshards=1)
				SpellAddTargetDebuff(soul_swap_soulburn agony_debuff=1 corruption_debuff=1 unstable_affliction_debuff=1)
			Define(soulburn 74434)
				SpellInfo(soulburn cd=1 gcd=0 soulshards=1)
				SpellAddBuff(soulburn soulburn_buff=1)
			Define(summon_abyssal 112921)
				SpellInfo(summon_abyssal cd=600)
			Define(summon_abyssal_demonic_servitude 157899)
			Define(summon_darkglare 205180)
				SpellInfo(summon_darkglare soulshards=1 cd=24)
			Define(summon_doomguard 18540)
				SpellInfo(summon_doomguard cd=180 gcd=1.5 soulshards=1)
				SpellInfo(summon_doomguard replace=summon_doomguard_demonic_servitude talent=grimoire_of_supremacy_talent)
			Define(summon_doomguard_demonic_servitude 157757)
			Define(summon_felguard 30146)
			Define(summon_felhunter 691)
			Define(summon_imp 688)
			Define(summon_infernal 1122)
				SpellInfo(summon_infernal cd=180 gcd=1.5 soulshards=1)
				SpellInfo(summon_infernal replace=summon_infernal_demonic_servitude talent=grimoire_of_supremacy_talent)
			Define(summon_infernal_demonic_servitude 157898)
			Define(summon_succubus 712)
			Define(summon_terrorguard 112927)
				SpellInfo(summon_terrorguard cd=600)
			Define(summon_terrorguard_demonic_servitude 157897)
			Define(summon_voidwalker 697)
			Define(t18_class_trinket 124522)
			Define(the_codex_of_xerrath 101508)
			Define(unending_resolve 104773)
				SpellInfo(unending_resolve cd=180 gcd=0)
				SpellAddBuff(unending_resolve unending_resolve_buff=1)
			Define(unstable_affliction 30108)
				SpellInfo(unstable_affliction gcd=1.5 soulshards=1)
				SpellAddTargetDebuff(unstable_affliction unstable_affliction_debuff=1)
			Define(wrathguard_mortal_cleave 115625)
				SpellInfo(wrathguard_mortal_cleave gcd=0)
				#SpellInfo(wrathguard_mortal_cleave energy=60)
				SpellAddTargetDebuff(wrathguard_mortal_cleave wrathguard_mortal_cleave_debuff=1)
			Define(wrathguard_wrathstorm 115831)
				SpellInfo(wrathguard_wrathstorm cd=45 gcd=0)

			# Buffs
			Define(backdraft_buff 117828)
				SpellInfo(backdraft_buff duration=15 max_stacks=3)
			Define(chaotic_infusion_buff 170000)
				SpellInfo(chaotic_infusion_buff duration=30)
			Define(compounding_horror_buff 199281)
				SpellAddBuff(unstable_affliction compounding_horror_buff=0)
			Define(conflagration_of_chaos_buff 219195)
			Define(dark_intent_buff 109773)
				SpellInfo(dark_intent_buff duration=3600)
			Define(dark_pact_buff 108416)
				SpellInfo(dark_pact_buff duration=20)
			Define(dark_soul_instability_buff 113858)
				SpellInfo(dark_soul_instability_buff duration=20)
			Define(dark_soul_knowledge_buff 113861)
				SpellInfo(dark_soul_knowledge_buff duration=20)
			Define(dark_soul_misery_buff 113860)
				SpellInfo(dark_soul_misery_buff duration=20)
			Define(demon_rush_buff 188857)
				SpellInfo(demon_rush_buff duration=15 max_stacks=5)
			Define(demonbolt_buff 157695)
				SpellInfo(demonbolt_buff duration=40 max_stacks=10 stacking=1)
			Define(demonic_calling_buff 205146)
				SpellInfo(demonic_calling_buff duration=20)
				SpellRequire(call_dreadstalkers soulshards 0=buff,demonic_calling_buff)
			Define(demonic_power_buff 196099)
				SpellInfo(demonic_power_buff duration=3600)
			Define(demonic_synergy_buff 171982)
				SpellInfo(demonic_synergy_buff duration=15)
			Define(ember_master_buff 145164)	# tier16_4pc_caster
				SpellInfo(ember_master_buff duration=5)
			Define(embrace_chaos_buff 212019)
				SpellInfo(embrace_chaos_buff duration=4)
			Define(empowered_life_tap_buff 235156)
				SpellInfo(empowered_life_tap_buff duration=20)
			Define(fire_and_brimstone_buff 108683)
			Define(grimoire_of_sacrifice_buff 196099)
				SpellInfo(grimoire_of_sacrifice_buff duration=3600)
			Define(haunting_spirits_buff 157698)
				SpellInfo(haunting_spirits_buff duration=30)
			Define(havoc_buff 80240)
				SpellInfo(havoc_buff duration=15 max_stacks=3)
			Define(kiljaedens_cunning_buff 137587)
				SpellInfo(kiljaedens_cunning_buff duration=8)
			Define(lord_of_flames_buff 224103) #TODO Not sure
			Define(mana_tap_buff 196104)
				SpellInfo(mana_tap_buff duration=20)
			Define(mannoroths_fury_buff 108508)
				SpellInfo(mannoroths_fury_buff duration=10)
			Define(shard_instability_buff 216457)
			Define(soul_harvest_buff 196098)
			Define(soul_swap_buff 86211)
				SpellInfo(soul_swap_buff duration=3)
			Define(soulburn_buff 74434)
				SpellInfo(soulburn_buff duration=30)
			Define(unending_resolve_buff 104773)
				SpellInfo(unending_resolve_buff duration=8)

			# Buff Spell Lists
			SpellList(molten_core_buff fel_molten_core_aura molten_core_aura)
			
			# Debuffs
			Define(agony_debuff 980)
				SpellInfo(agony_debuff duration=24 haste=spell max_stacks=10 talent=!writhe_in_agony_talent)
				SpellInfo(agony_debuff duration=24 haste=spell max_stacks=20 talent=writhe_in_agony_talent)
			Define(corruption_debuff 146739)
				SpellInfo(corruption_debuff duration=18 haste=spell tick=2)
			Define(doom_debuff 603)
				SpellInfo(doom_debuff duration=20)
			Define(eradication_debuff 196414)
				SpellInfo(eradication_debuff duration=6)
			Define(flamelicked_debuff 185229)
				SpellInfo(flamelicked_debuff duration=10 max_stacks=5)
			Define(haunt_debuff 48181)
				SpellInfo(haunt_debuff duration=8 haste=spell tick=2)
				SpellInfo(haunt_debuff addduration=2 if_spell=enhanced_haunt)
			Define(havoc_debuff 80240)
				SpellInfo(havoc_debuff duration=8)
				SpellInfo(havoc_debuff addduration=12 talent=wreak_havoc_talent)
			Define(immolate_debuff 157736)
				SpellInfo(immolate_debuff duration=18 haste=spell tick=3)
			Define(mark_of_doom_debuff 184073)
				SpellInfo(mark_of_doom_debuff duration=10)
			Define(rain_of_fire_debuff 5740)
				SpellInfo(rain_of_fire_debuff duration=8 haste=spell tick=1)
			Define(roaring_blaze_debuff 205184) #TODO Check this
			Define(seed_of_corruption_soulburn_debuff 114790)
				SpellInfo(seed_of_corruption_soulburn_debuff duration=18 tick=3)
			Define(shadowflame_debuff 205181)
				SpellInfo(shadowflame_debuff duration=8 haste=spell tick=2)
			Define(siphon_life_debuff 63106)
				SpellInfo(siphon_life_debuff duration=15 tick=3)
			Define(soul_effigy_debuff 205178)
			Define(unstable_affliction_debuff 30108)
				SpellInfo(unstable_affliction_debuff duration=8 haste=spell)
			Define(wrathguard_mortal_cleave_debuff 115625)
				SpellInfo(wrathguard_mortal_cleave_debuff duration=6)

			# Debuff Spell Lists
			SpellList(seed_of_corruption_debuff seed_of_corruption_aura seed_of_corruption_soulburn_debuff)
			
			# Artifact
			Define(dimensional_rift 196586)
				SpellInfo(dimensional_rift cd=45)
			Define(reap_souls 216698)
			Define(thalkiels_consumption 211714)
				SpellInfo(thalkiels_consumption cd=45)

			Define(lord_of_flames_trait 224103)

			Define(deadwind_harvester_buff 214867)
				SpellAddBuff(reap_souls tormented_souls_buff=0)
			Define(tormented_souls_buff 216695)
		]];

		OvaleScripts:RegisterScript("WARLOCK", nil, name, desc, code, "include");
	end
end