local addonName, addonTable = ...; -- Pulls back the Addon-Local Variables and store them locally.
local FORCE_DEBUG = false;

if LunaEclipse_Scripts:isCompatableWOWVersion() and LunaEclipse_Scripts:isRequiredOvaleVersion(addonTable.REQUIRED_OVALE_VERSION) then
	local OvaleScripts = addonTable.Ovale.OvaleScripts;

	do
		local name = "lunaeclipse_warrior_spells";
		local desc = "LunaEclipse: Warrior spells";
		local code = [[
			# Warrior spells and functions
			Define(meat_cleaver 12950)
				SpellInfo(meat_cleaver learn=1 level=58 specialization=fury)
			Define(unwavering_sentinel 29144)
				SpellInfo(unwavering_sentinel learn=1 level=10 specialization=protection)
			Define(avatar 107574)
				SpellInfo(avatar cd=90 gcd=0)
			Define(avatar_buff 107574)
				SpellInfo(avatar_buff duration=20)
			Define(battle_cry 1719)
				SpellInfo(battle_cry cd=60)
				SpellInfo(battle_cry rage=-100 talent=reckless_abandon_talent)
				SpellAddBuff(battle_cry battle_cry_buff=1)
			Define(battle_cry_buff 1719)
				SpellInfo(battle_cry_buff duration=5)
				SpellInfo(battle_cry_buff addduration=1 itemset=T19 itemcount=2 specialization=arms)
			Define(berserker_rage 18499)
				SpellInfo(berserker_rage cd=60 gcd=0)
				SpellInfo(berserker_rage rage=-20 itemset=T20 itemcount=2 specialization=protection)
				SpellAddBuff(berserker_rage berserker_rage_buff=1)
				SpellAddBuff(berserker_rage enrage_buff=1 specialization=fury talent=outburst_talent)
			Define(berserker_rage_buff 18499)
				SpellInfo(berserker_rage_buff duration=6)
			Define(bladestorm 227847)
				SpellInfo(bladestorm cd=90 channel=6 haste=melee)
			Define(bloodbath 12292)
				SpellInfo(bloodbath cd=30 gcd=0)
				SpellAddBuff(bloodbath bloodbath_buff=1)
			Define(bloodbath_buff 12292)
				SpellInfo(bloodbath_buff duration=10)
			Define(bloodthirst 23881)
				SpellInfo(bloodthirst cd=4.5 rage=-10)
				SpellAddBuff(bloodthirst meat_cleaver_buff=-1)
			Define(charge 100)
				SpellInfo(charge cd=20 gcd=0 offgcd=1 rage=-20 travel_time=1 max_charge=1)
				SpellInfo(charge addcd=-3 max_charge=2 talent=double_time_talent)
				SpellAddTargetDebuff(charge charge_debuff=1)
			Define(cleave 845)
				SpellInfo(cleave cd=6 cd_haste=melee rage=10)
				SpellInfo(cleave rage_percent=90 talent=dauntless_talent)
				SpellRequire(cleave rage_percent 25=buff,battle_cry_buff talent=deadly_calm_talent)
			Define(cleave_buff 188923)
			Define(colossus_smash 167105)
				SpellInfo(colossus_smash cd=20)
				SpellInfo(colossus_smash addcd=-8 talent=titanic_might_talent)
				SpellAddBuff(colossus_smash in_for_the_kill_buff=1 if_spell=in_for_the_kill)
				SpellAddTargetDebuff(colossus_smash colossus_smash_debuff=1)
			Define(colossus_smash_debuff 208086)
				SpellInfo(colossus_smash_debuff duration=8)
				SpellInfo(colossus_smash_debuff addduration=8 talent=titanic_might_talent)
			Define(commanding_shout 97462)
				SpellInfo(commanding_shout cd=180 gcd=0 offgcd=1)
				SpellAddBuff(commanding_shout commanding_shout_buff=1)
			Define(commanding_shout_buff 97463)
				SpellInfo(commanding_shout_buff duration=10)
			Define(deep_wounds 115768)
			Define(deep_wounds_debuff 115767)
				SpellInfo(deep_wounds_debuff duration=15 tick=3)
			Define(demoralizing_shout 1160)
				SpellInfo(demoralizing_shout cd=90 gcd=0 offgcd=1)
				SpellRequire(demoralizing_shout rage -60 talent=booming_voice_talent)
				SpellAddTargetDebuff(demoralizing_shout demoralizing_shout_debuff=1)
			Define(demoralizing_shout_debuff 1160)
				SpellInfo(demoralizing_shout_debuff duration=8)
			Define(devastate 20243)
				SpellAddTargetDebuff(devastate deep_wounds_debuff=1 if_spell=deep_wounds)
			Define(dragon_roar 118000)
				SpellInfo(dragon_roar cd=25)
				SpellAddBuff(dragon_roar dragon_roar_buff=1)
			Define(dragon_roar_buff 118000)
				SpellInfo(dragon_roar_buff duration=6)
			Define(enrage_buff 184362)
				SpellInfo(enrage_buff duration=4)
				SpellInfo(enrage_buff addduration=1 itemset=T19 itemcount=4)
			Define(enraged_regeneration 184364)
				SpellInfo(enraged_regeneration cd=120 gcd=0 offgcd=1)
			Define(enraged_regeneration_buff 184364)
				SpellInfo(enraged_regeneration_buff duration=8)
			Define(execute 5308)
				SpellInfo(execute rage=25)
				SpellAddBuff(execute juggernaut_buff=1)
				SpellAddBuff(execute sense_death_buff=0)
				SpellRequire(execute rage 0=stone_heart_buff)
			Define(execute_arms 163201)
				SpellInfo(execute_arms rage=10 extra_rage=30)
				SpellInfo(execute_arms rage_percent=90 talent=dauntless_talent)
				SpellRequire(execute_arms rage_percent 25=buff,battle_cry_buff talent=deadly_calm_talent)
				SpellRequire(execute_arms rage 0=stone_heart_buff)
				SpellAddBuff(execute_arms executioners_precision_buff=1 if_spell=executioners_precision)
			Define(executioners_precision 238147)
			Define(executioners_precision_buff 242188)
				SpellInfo(executioners_precision_buff duration=30 max_stacks=2)
			Define(focused_rage 207982)
				SpellInfo(focused_rage cd=1.5 cd_haste=melee gcd=0 offgcd=1 rage=20)
				SpellInfo(focused_rage rage_percent=90 talent=dauntless_talent)
				SpellRequire(focused_rage rage_percent 25=buff,battle_cry_buff talent=deadly_calm_talent)
				SpellAddBuff(focused_rage focused_rage_buff=1)
				SpellInfo(focused_rage replace=focused_rage_protection specialization=protection)
			Define(focused_rage_buff 207982)
				SpellInfo(focused_rage_buff duration=30)
			Define(focused_rage_protection 204488)
				SpellInfo(focused_rage_protection cd=1.5 cd_haste=melee rage=30)
				SpellAddBuff(focused_rage_protection focused_rage_protection_buff=1)
			Define(focused_rage_protection_buff 204488)
				SpellInfo(focused_rage_protection_buff duration=30)
			Define(frenzy_buff 202539)
				SpellInfo(frenzy_buff duration=15 max_stacks=3)
			Define(frothing_berserker_buff 215572)
				SpellInfo(frothing_berserker_buff duration=6)
			Define(furious_slash 100130)
				SpellAddBuff(furious_slash frenzy_buff=1 talent=frenzy_talent)
			Define(hamstring 1715)
				SpellInfo(hamstring cd=1 gcd=0 offgcd=1 rage=8)
				SpellAddTargetDebuff(hamstring hamstring_debuff=1)
			Define(hamstring_debuff 1715)
				SpellInfo(hamstring_debuff duration=15)
			Define(heroic_leap 6544)
				SpellInfo(heroic_leap cd=45 gcd=0 offgcd=1 travel_time=1)
				SpellInfo(heroic_leap addcd=-15 talent=bounding_stride_talent)
				SpellAddBuff(heroic_leap heroic_leap_buff=1 talent=bounding_stride_talent)
			Define(heroic_leap_buff 202164)
			Define(heroic_throw 57755)
				SpellInfo(heroic_throw cd=6 travel_time=1)
				SpellInfo(heroic_throw addcd=-6 specialization=protection)
			Define(ignore_pain 190456)
				SpellInfo(ignore_pain cd=1 gcd=0 offgcd=1 rage=20 extra_rage=40)
				SpellAddBuff(ignore_pain ignore_pain_buff=1)
				SpellAddBuff(ignore_pain vengeance_revenge_buff=1 talent=vengeance_talent)
				SpellAddBuff(ignore_pain vengeance_ignore_pain_buff=-1 talent=vengeance_talent)
			Define(ignore_pain_buff 190456)
				SpellInfo(ignore_pain duration=15)
			Define(impending_victory 202168)
				SpellInfo(impending_victory rage=10 cd=30)
				SpellRequire(impending_victory cd 0=victorious_buff)
				SpellAddBuff(impending_victory victorious_buff=0)
			Define(in_for_the_kill 248621)
			Define(in_for_the_kill_buff 248622)
			Define(intercept 198304)
				SpellInfo(intercept cd=20 rage=-15 gcd=0 offgcd=1)
			Define(juggernaut 200875)
				SpellAddBuff(execute juggernaut_buff=1 if_spell=juggernaut)
			Define(juggernaut_buff 201009)
				SpellInfo(juggernaut_buff duration=8 max_stacks=99)
			Define(last_stand 12975)
				SpellInfo(last_stand cd=180 gcd=0 offgcd=1)
				SpellAddBuff(last_stand last_stand_buff=1)
			Define(last_stand_buff 12975)
				SpellInfo(last_stand_buff duration=15)
			Define(massacre_buff 206316)
			Define(meat_cleaver_buff 85739)
				SpellInfo(meat_cleaver_buff duration=10)
			Define(mortal_strike 12294)
				SpellInfo(mortal_strike cd=6 cd_haste=melee rage=20)
				SpellInfo(mortal_strike rage_percent=90 talent=dauntless_talent)
				SpellInfo(mortal_strike charges=2 talent=mortal_combo_talent)
				SpellRequire(mortal_strike rage_percent 25=buff,battle_cry_buff talent=deadly_calm_talent)
				SpellAddTargetDebuff(mortal_strike mortal_wounds_debuff=1)
			Define(mortal_wounds_debuff 115804)
				SpellInfo(mortal_wounds_debuff duration=10)
			Define(odyns_fury 205545)
				SpellInfo(odyns_fury cd=45)
			Define(overpower 7384)
				SpellAddBuff(overpower overpower_buff=-1)
				SpellRequire(overpower unusable 1=buff,!overpower_buff)
			Define(overpower_buff 60503)
				SpellInfo(overpower_buff duration=12)
			Define(precise_strikes_buff 164323)
			Define(pummel 6552)
				SpellInfo(pummel cd=15 gcd=0 interrupt=1 offgcd=1)
			Define(raging_blow 85288)
				SpellInfo(raging_blow rage=-5)
				SpellInfo(raging_blow cd=4.5 cd_haste=melee talent=inner_rage_talent)
				SpellRequire(raging_blow unusable 1=buff,!enrage_buff talent=!inner_rage_talent)
			Define(rampage 184367)
				SpellInfo(rampage gcd=1.5 cd_haste=none rage=85)
				SpellInfo(rampage rage=70 talent=carnage_talent)
				SpellAddBuff(rampage enrage_buff=1)
				SpellAddBuff(rampage meat_cleaver_buff=-1)
				SpellRequire(rampage rage 0=buff,massacre_buff talent=massacre_talent)
			Define(rampage_buff 166588) #T17 4 piece
				SpellInfo(rampage_buff duration=5)
			Define(ravager 152277)
				SpellInfo(ravager cd=60)
				SpellInfo(ravager ravager_buff=1)
				SpellInfo(ravager replace=ravager_protection specialization=protection)
			Define(ravager_buff 152277)
				SpellInfo(ravager_buff duration=7 haste=melee)
			Define(ravager_protection 228920)
				SpellAddBuff(ravager_protection ravager_protection_buff=1)
			Define(ravager_protection_buff 227744)
				SpellInfo(ravager_protection_buff duration=10)
			Define(rend 772)
				SpellInfo(rend rage=30)
				SpellInfo(rend rage_percent=90 talent=dauntless_talent)
				SpellRequire(rend rage_percent 25=buff,battle_cry_buff talent=deadly_calm_talent)
				SpellAddTargetDebuff(rend rend_debuff=1)
			Define(rend_debuff 772)
				SpellInfo(rend_debuff duration=8)
			Define(revenge 6572)
				# do not add a rage cost, free revenges do not have an aura and thus we cannot set the rage and the SpellRequire.
				# OvalePower:Power will fall back to using OvalePower:GetSpellCost() which will give the actual (and current) rage cost
				SpellInfo(revenge cd=9 cd_haste=melee)
				SpellAddBuff(revenge vengeance_ignore_pain_buff=1 talent=vengeance_talent)
				SpellAddBuff(revenge vengeance_revenge_buff=-1 talent=vengeance_talent)
				SpellAddTargetDebuff(devastate deep_wounds_debuff=1 if_spell=deep_wounds)
			Define(sense_death_buff 200979)
				SpellRequire(execute rage 0=buff,sense_death_buff)
				SpellRequire(execute_arms rage 0=buff,sense_death_buff)
			Define(shattered_defenses_buff 248625)
			Define(shield_block 2565)
				SpellInfo(shield_block cd=13 cd_haste=melee gcd=0 offgcd=1 rage=15)
			Define(shield_block_buff 132404)
				SpellInfo(shield_block_buff duration=6)
			Define(shield_slam 23922)
				SpellInfo(shield_slam cd=9 cd_haste=melee rage=-20)
			Define(shield_wall 871)
				SpellInfo(shield_wall cd=240 gcd=0 offgcd=1)
				SpellAddBuff(shield_wall shield_wall_buff=1)
			Define(shield_wall_buff 871)
				SpellInfo(shield_wall duration=8)
			Define(shockwave 46968)
				SpellInfo(shockwave cd=40)
			Define(slam 1464)
				SpellInfo(slam rage=20)
				SpellInfo(slam rage_percent=90 talent=dauntless_talent)
				SpellRequire(slam rage_percent 25=buff,battle_cry_buff talent=deadly_calm_talent)
			Define(spell_reflection 23920)
				SpellInfo(spell_reflection cd=25)
			Define(stone_heart_buff 225947)
			Define(storm_bolt 107570)
				SpellInfo(storm_bolt cd=30)
			Define(t18_class_trinket 124523)
			Define(taunt 355)
				SpellInfo(taunt cd=8)
				SpellInfo(taunt addcd=-8 if_buff=berserker_rage_buff talent=warlords_challenge_talent)
			Define(thunder_clap 6343)
				SpellInfo(thunder_clap cd=6 cd_haste=melee rage=-5)
			Define(ultimatum_buff 122510)
				SpellInfo(ultimatum_buff duration=10)
			Define(unquenchable_thirst 169683)
			Define(unyielding_strikes 169685)
			Define(unyielding_strikes_buff 169686)
				SpellInfo(unyielding_strikes_buff duration=5 max_stacks=6 stacking=1)
			Define(vengeance_revenge_buff 202573)
				SpellRequire(revenge rage_percent 65=buff,vengeance_revenge_buff)
			Define(vengeance_ignore_pain_buff 202574)
				SpellRequire(ignore_pain rage_percent 65=buff,vengeance_ignore_pain_buff)
			Define(victorious_buff 32216)
				SpellInfo(victorious_buff duration=20)
			Define(victory_rush 34428)
				SpellRequire(victory_rush unusable 1=buff,!victorious_buff)
				SpellAddBuff(victory_rush victorious_buff=0)
			Define(warbreaker 209577)
				SpellInfo(warbreaker cd=60)
			Define(whirlwind 1680)
				SpellInfo(whirlwind rage=30 specialization=arms)
				SpellInfo(whirlwind rage_percent=90 talent=dauntless_talent specialization=arms)
				SpellAddBuff(whirlwind meat_cleaver_buff=1)
				SpellAddBuff(whirlwind wrecking_ball_buff=0)
			Define(wrecking_ball_buff 215570)
				SpellInfo(wrecking_ball_buff duration=12)

			# Talents Common
			Define(double_time_talent 6)
			Define(avatar_talent 9)
			Define(bounding_stride_talent 11)
			Define(bladestorm_talent 19)

			# Talents Arms
			Define(dauntless_talent 1)
			Define(overpower_talent 2)
			Define(sweeping_strikes_talent 3)
			Define(shockwave_talent 4)
			Define(storm_bolt_talent 5)
			Define(rend_talent 8)
			Define(fervor_of_battle_talent 13)
			Define(mortal_combo_talent 14)
			Define(titanic_might_talent 15)
			Define(deadly_calm_talent 16)
			Define(in_for_the_kill_talent 17)
			Define(focused_rage_talent 18)
			Define(anger_management_talent 19)
			Define(ravager_talent 21)

			# Talents Fury
			Define(wrecking_ball_talent 7)
			Define(outburst_talent 8)
			Define(warlords_challenge_talent 10)
			Define(massacre_talent 13)
			Define(frothing_berserker_talent 14)
			Define(carnage_talent 15)
			Define(bloodbath_talent 16)
			Define(frenzy_talent 17)
			Define(inner_rage_talent 18)
			Define(reckless_abandon_talent 20)
			Define(dragon_roar_talent 21)

			# Talents Protection
			Define(impending_victory_talent 4)
			Define(devastator_talent 13)
			Define(vengeance_talent 16)
			Define(booming_voice_talent 18)
			Define(heavy_repercussions_talent 20)
			Define(ravager_talent 21)

			# Artifacts
			Define(neltharions_fury 203524)
				SpellInfo(neltharions_fury cd=45)
			Define(neltharions_fury_buff 203524)
				SpellInfo(neltharions_fury_buff duration=3)
			
		]];

		OvaleScripts:RegisterScript("WARRIOR", nil, name, desc, code, "include");
	end
end